---
title: "R Notebook"
output: html_notebook
---

code development for plotting the plate layout

adapting, probably from echowritr!

```{r}
library(tidyverse)
library(tidyplate) # woohoo!
```

Get a sample layout
```{r}
SAMPLE_LAYOUTS <- fs::dir_ls("../01-sample_inputs")
layout <-  read_layout("../01-sample_inputs/test_standard_read.xlsx", .print_summary = FALSE, plate_notes = "adding my own custom plate note here") 
```

Plot a single variable
```{r}
plate_plot <- plot_plate_variable(layout, "final_test_conc")
plate_plot
```


#### development only below this line
Style and source the function script
```{r}
PATH <- "../00-function_development/01-updated_functions/plot_plate.R"
styler::style_file(PATH)
source(PATH)
```
Get a sample layout
```{r}
SAMPLE_LAYOUTS <- fs::dir_ls("../01-sample_inputs")
layout <-  read_layout("../01-sample_inputs/test_standard_read.xlsx", .print_summary = TRUE, plate_notes = "adding my own custom plate note here") 
```

Plot a single variable
```{r}
plate_plot <- plateview_plot(layout, "cmpd",  caption = "caption here", subtitle =" subtitle here")
```

Plot the layout
```{r}
plate_theme_light <-
  function(aspect_ratio = 16/24,
           grid_color = "grey",
           grid_linewidth = 0.2,
           master_text_size = 12,
           ...) {
    
    title_size <- master_text_size*1
    subtitle_size <- master_text_size*0.8
    axis_text_size <- master_text_size*0.8
    
    theme(
      aspect.ratio = aspect_ratio,
      
      panel.background  =
        element_rect(
          color = "transparent",
          fill = "transparent"),
      
      panel.grid.minor =
        element_blank(),
      
      panel.grid.major =
        element_line(
          color = grid_color,
          linewidth = grid_linewidth), 
      
      axis.ticks = element_line(
          color = grid_color,
          linewidth = grid_linewidth), 
      
      axis.title =
        element_blank(),
      
      plot.background =
        element_rect(
          fill = "transparent",
          colour = NA),
    
    text = element_text(size = master_text_size),
    plot.title = element_text(face = "bold")
    )
  }

plateview_plot <-
  function(layout,
           fill_col,
           title = NULL,
           subtitle = NULL,
           caption = NULL,
           scale_plot_size = 1,
           .well_shape = 22,
           master_text_size = 16,
           well_size = 4,
           .well_outline_color = "#969696",
           show_empty_wells = TRUE,
           .fill_scale = NULL,
           .max_legend_size = 12,
           ...) {
    
    ####---- variable as title, unless otherwise given
   if(is.null(title)) {
     title <- fill_col
   } 
    
    # resize geoms and text together
    plot_sizes <- scale_plot_size*c(well_size = well_size, 
                                    well_stroke = 0.5,
                       master_text_size = master_text_size,
                       
                       grid_linewidth = 0.2)
    
    
    ####---- add missing wells to layout
    if(show_empty_wells){
      layout<- tidyplate::add_missing_wells(layout)
    }
    
    # determine the x axis breaks
    first_col <- min(layout$column)
    last_col = max(layout$column)
    
    # determine fill scale and guide type
    if(is.numeric(layout[[fill_col]])) {
        fill_scale <- scale_fill_viridis_c(na.value = "transparent")
        guide_type <- "numeric"
        guide_position <- "right"
      } else {
        fill_scale <- scale_fill_viridis_d(option = "turbo")
        guide_type <- "discrete"
        
        ## only show guide if it would fit well in the screen ... 
        # determine if the guides should be shown or not
        n_values <- n_distinct(layout[[fill_col]])
        guide_position <- ifelse(n_values > .max_legend_size,
                                  yes = "none",
                                  no = "right")
      }
  
    p <- 
      ggplot(layout, aes(x = .data$column, 
                         y = .data$row)) +
      
      geom_point(aes(fill = .data[[fill_col]]),
                 shape = .well_shape, 
                 stroke = plot_sizes[["well_stroke"]],
                 size = plot_sizes[["well_size"]]) +
      
      scale_y_discrete(limits = rev) + # start with row A
      scale_x_continuous(breaks = seq(from = first_col, to = last_col, by = 1))+
      fill_scale +
      plate_theme_light(grid_linewidth = plot_sizes[["grid_linewidth"]],
           master_text_size = plot_sizes[["master_text_size"]],
           ...) +
      
      # determined by the type and number of values in the variable
      theme(legend.position = guide_position) + 
      
      labs(title = title,
           subtitle = subtitle,
           caption = caption)
    
    # don't allow more than ten rows for discrete legends
    if (guide_type == "discrete") {
      p <- p + guides(fill = guide_legend(nrow = 10))
    }
    
    p
    
  }


plate_plot <- plateview_plot(layout %>% filter(column < 9), "cmpd", title = "my custom title", caption = "caption here", subtitle =" subtitle here")

```

```{r}
plot_all_variables <- function(layout, .exclude_columns = c("well", "row", "column", "condition"), ...){
  variables <- names(layout)[!names(layout) %in% .exclude_columns]
  all_plots <- list()
  for(variable in variables){
    p <- plateview_plot(layout = layout, fill_col = variable, title_var = variable, ...)
    all_plots[[variable]] <- p
  }
all_plots
}
```


```{r}
all_plots <- plot_all_variables(layout, scale_plot_size = 0.5)


patchworked <- patchwork::wrap_plots(all_plots, ncol = 2)

ggsave("../04-sample_outputs/plots/patchwork_plot.pdf", patchworked, width = 7, height = 10)
```


Summary plate
```{r}
library(patchwork)
# with_notes <- layout |> 
#   mutate( well_notes = NA, 
#           plate_notes = list(rep(list("i made an experimental note", "and then i made another one", "and finally i made a third one which is really really long and i don't want it to get cut off or wrap poorly or whatever"), times = 360),
#         )
        
layout_summary <-  summarise_plate(layout,  use_crayon = FALSE)

plate_plot <- plateview_plot(layout, fill_col = "purity", title_var = "purity")

plate_plot + grid::textGrob(layout_summary, gp = grid::gpar(fontsize = 10, col="grey"), check.overlap=TRUE)     


annotated <- plate_plot + 
  plot_annotation(
  title = 'The surprising truth about mtcars',
  subtitle = reformatted, 
  caption = 'Disclaimer: None of these plots are insightful'
) 

annotated

ggsave("../04-sample_outputs/plots/patchwork_plot_summary.pdf", annotated, width = 7, height = 10)

reformatted <- gsub(layout_summary, pattern = "\n", replacement = " ") |> gsub(pattern = " >> ", replacement = "\n")
reformatted
```


Style the function script
```{r}
styler::style_file("../00-function_development/01-updated_functions/read_plate_layout.R")
```

Read in the script containing the function to test
```{r}
source("../00-function_development/01-updated_functions/read_plate_layout.R")
# read_plate_layout
```



